export type VideoShortType = {
    /** Invidious: обычное видео или шорт (`shortVideo`). */
    type: "video" | "shortVideo",
    title: string,
    videoId: string,
    author: string,
    authorId: string,
    authorUrl: string,
    videoThumbnails: [
      {
        quality: string,
        url: string,
        width: number,
        height: number
      }
    ],
    description: string,
    descriptionHtml: string,
    viewCount: number,
    published: number,
    publishedText: string,
    lengthSeconds: number,
    liveNow: boolean,
    paid: boolean,
    premium: boolean

}

export type PlaylistShortType = {
  type: "playlist",
  title: string,
  playlistId: string,
  playlistThumbnail: string,
  author: string,
  authorId: string,
  authorUrl: string,
  authorVerified: boolean,

  videoCount: number,
  videos: [
    {
      title: string,
      videoId: string,
      lengthSeconds: number,
      videoThumbnails: [
        {
          quality: string,
          url: string,
          width: number,
          height: number
        }
      ]
    }
  ]
}

export type ChannelShortType = {
  type: "channel",
  author: string,
  authorId: string,
  authorUrl: string,

  authorThumbnails: [
    {
      url: string,
      width: number,
      height: number
    }
  ],
  autoGenerated: boolean
  subCount: number,
  videoCount: number,
  description: string,
  descriptionHtml: string
}

export type HashtagShortType = {
    type: "hashtag"
    title: string,
    url: string,
    channelCount: number,
    videoCount: number
  }

/** Элемент сетки ленты / поиска: ролик, плейлист или канал. */
export type VideoGridItemType = VideoShortType | PlaylistShortType | ChannelShortType | HashtagShortType

export type SubscriptionType = {
  /** UCID канала (для подписки / проверки). */
  authorId: string
  avatar: string
  name: string
  url: string
  verified: boolean
}
