export const RTK_TAGS = {
  SEARCH: "SEARCH",
  STREAM: "STREAM",
  CHANNEL: "CHANNEL",
  PLAYLIST: "PLAYLIST",
  FEED: "FEED",
  SUBSCRIPTIONS: "SUBSCRIPTIONS",
  IS_SUBSCRIBED: "IS_SUBSCRIBED",
  USER_PLAYLISTS: "USER_PLAYLISTS",
  AUTH: "AUTH",
} as const
